// Map of station codes to full names
export const STATION_NAMES: Record<string, string> = {
  // FRV Stations (both P and FS prefixes map to same names)
  'P45': 'FRV 45 (Brooklyn)',
  'FS45': 'FRV 45 (Brooklyn)',
  'P47': 'FRV 47 (Footscray)',
  'FS47': 'FRV 47 (Footscray)',
  'P77': 'FRV 77 (Traralgon)',
  'FS77': 'FRV 77 (Traralgon)',
  'P78': 'FRV 78 (Morwell)',
  'FS78': 'FRV 78 (Morwell)',
  'P92': 'FRV 92 (Cranbourne)',
  'FS92': 'FRV 92 (Cranbourne)',
  'P88': 'FRV 88 (Hallam)',
  'FS88': 'FRV 88 (Hallam)',
  'P40': 'FRV 40 (Laverton)',
  'FS40': 'FRV 40 (Laverton)',
  'P58': 'FRV 58 (Point Cook)',
  'FS58': 'FRV 58 (Point Cook)',
  'P34': 'FRV 34 (Highett)',
  'FS34': 'FRV 34 (Highett)',
  'P10': 'FRV 10 (Richmond)',
  'FS10': 'FRV 10 (Richmond)',
  'P13': 'FRV 13 (Northcote)',
  'FS13': 'FRV 13 (Northcote)',
  'P35': 'FRV 35 (Windsor)',
  'FS35': 'FRV 35 (Windsor)',
  'P15': 'FRV 15 (Heidelberg)',
  'FS15': 'FRV 15 (Heidelberg)',
  'P14': 'FRV 14 (Bundoora)',
  'FS14': 'FRV 14 (Bundoora)',
  'P07': 'FRV 7 (Thomastown)',
  'FS07': 'FRV 7 (Thomastown)',
  'P32': 'FRV 32 (Ormond)',
  'FS32': 'FRV 32 (Ormond)',
  'P87': 'FRV 87 (Dandenong)',
  'FS87': 'FRV 87 (Dandenong)',
  'P87A': 'FRV 87 (Dandenong)',
  'FS87A': 'FRV 87 (Dandenong)',
  'P87B': 'FRV 87B (Dandenong)',
  'FS87B': 'FRV 87B (Dandenong)',
  'P24': 'FRV 24 (Glen Iris)',
  'FS24': 'FRV 24 (Glen Iris)',
  'P25': 'FRV 25 (Oakleigh)',
  'FS25': 'FRV 25 (Oakleigh)',
  'P29': 'FRV 29 (Clayton)',
  'FS29': 'FRV 29 (Clayton)',
  'P72': 'FRV 72 (Mildura)',
  'FS72': 'FRV 72 (Mildura)',
  'P11': 'FRV 11 (Epping)',
  'FS11': 'FRV 11 (Epping)',
  'P89': 'FRV 89 (Springvale)',
  'FS89': 'FRV 89 (Springvale)',
  'P12': 'FRV 12 (Preston)',
  'FS12': 'FRV 12 (Preston)',
  'P59': 'FRV 59 (Derrimut)',
  'FS59': 'FRV 59 (Derrimut)',
  'P53': 'FRV 53 (Sunbury)',
  'FS53': 'FRV 53 (Sunbury)',
  'P02': 'FRV 2 (West Melbourne)',
  'FS02': 'FRV 2 (West Melbourne)',
  'P03': 'FRV 3 (Carlton)',
  'FS03': 'FRV 3 (Carlton)',
  'P01': 'FRV 1 (Eastern Hill)',
  'FS01': 'FRV 1 (Eastern Hill)',
  'P30': 'FRV 30 (Templestowe)',
  'FS30': 'FRV 30 (Templestowe)',
  'P82': 'FRV 82 (Eltham)',
  'FS82': 'FRV 82 (Eltham)',
  'P62': 'FRV 62 (Corio)',
  'FS62': 'FRV 62 (Corio)',
  'P62A': 'FRV 62 (Corio)',
  'FS62A': 'FRV 62 (Corio)',
  'P44': 'FRV 44 (Sunshine)',
  'FS44': 'FRV 44 (Sunshine)',
  'P51': 'FRV 51 (Keilor)',
  'FS51': 'FRV 51 (Keilor)',
  'P42': 'FRV 42 (Newport)',
  'FS42': 'FRV 42 (Newport)',
  'P55': 'FRV 55 (Caroline Springs)',
  'FS55': 'FRV 55 (Caroline Springs)',
  'P39': 'FRV 39 (Port Melbourne)',
  'FS39': 'FRV 39 (Port Melbourne)',
  'P38': 'FRV 38 (South Melbourne)',
  'FS38': 'FRV 38 (South Melbourne)',
  'P20': 'FRV 20 (Box Hill)',
  'FS20': 'FRV 20 (Box Hill)',
  'P43': 'FRV 43 (Deer Park)',
  'FS43': 'FRV 43 (Deer Park)',
  'P41': 'FRV 41 (St Albans)',
  'FS41': 'FRV 41 (St Albans)',
  'P27': 'FRV 27 (Nunawading)',
  'FS27': 'FRV 27 (Nunawading)',
  'P26': 'FRV 26 (Croydon)',
  'FS26': 'FRV 26 (Croydon)',
  'P52': 'FRV 52 (Tullamarine)',
  'FS52': 'FRV 52 (Tullamarine)',
  'P16': 'FRV 16 (Greensborough)',
  'FS16': 'FRV 16 (Greensborough)',
  'P56': 'FRV 56 (Melton)',
  'FS56': 'FRV 56 (Melton)',
  'P46': 'FRV 46 (Altona)',
  'FS46': 'FRV 46 (Altona)',
  'P61': 'FRV 61 (Lara)',
  'FS61': 'FRV 61 (Lara)',
  'P04': 'FRV 4 (Brunswick)',
  'FS04': 'FRV 4 (Brunswick)',
  'P31': 'FRV 31 (Glen Waverley)',
  'FS31': 'FRV 31 (Glen Waverley)',
  'PT31': 'FRV 31 (Glen Waverley)',
  'P48': 'FRV 48 (Taylors Lakes)',
  'FS48': 'FRV 48 (Taylors Lakes)',
  'P70': 'FRV 70 (Warrnambool)',
  'FS70': 'FRV 70 (Warrnambool)',
  'P28': 'FRV 28 (Vermont South)',
  'FS28': 'FRV 28 (Vermont South)',
  'P86': 'FRV 86 (Rowville)',
  'FS86': 'FRV 86 (Rowville)',
  'P93': 'FRV 93 (Pakenham)',
  'FS93': 'FRV 93 (Pakenham)',
  'P63': 'FRV 63 (Geelong)',
  'FS63': 'FRV 63 (Geelong)',
  'P91': 'FRV 91 (Frankston)',
  'FS91': 'FRV 91 (Frankston)',
  'P91B': 'FRV 91B (Frankston)',
  'FS91B': 'FRV 91B (Frankston)',
  'P22': 'FRV 22 (Ringwood)',
  'FS22': 'FRV 22 (Ringwood)',
  'P74': 'FRV 74 (Wangaratta)',
  'FS74': 'FRV 74 (Wangaratta)',
  'P81': 'FRV 81 (South Morang)',
  'FS81': 'FRV 81 (South Morang)',
  'P75': 'FRV 75 (Shepparton)',
  'FS75': 'FRV 75 (Shepparton)',
  'P64': 'FRV 64 (Belmont)',
  'FS64': 'FRV 64 (Belmont)',
  'P66': 'FRV 66 (Ocean Grove)',
  'FS66': 'FRV 66 (Ocean Grove)',
  'P23': 'FRV 23 (Burwood)',
  'FS23': 'FRV 23 (Burwood)',
  'P80': 'FRV 80 (Craigieburn)',
  'FS80': 'FRV 80 (Craigieburn)',
  'P57': 'FRV 57 (Tarneit)',
  'FS57': 'FRV 57 (Tarneit)',
  'P18': 'FRV 18 (Hawthorn)',
  'FS18': 'FRV 18 (Hawthorn)',
  'P76': 'FRV 76 (Wodonga)',
  'FS76': 'FRV 76 (Wodonga)',
  'P73': 'FRV 73 (Bendigo)',
  'FS73': 'FRV 73 (Bendigo)',
  'P73A': 'FRV 73A (Bendigo)',
  'FS73A': 'FRV 73A (Bendigo)',
  'P73B': 'FRV 73B (Bendigo)',
  'FS73B': 'FRV 73B (Bendigo)',
  'P06': 'FRV 6 (Pascoe Vale)',
  'FS06': 'FRV 6 (Pascoe Vale)',
  'P05': 'FRV 5 (Broadmeadows)',
  'FS05': 'FRV 5 (Broadmeadows)',
  'P19': 'FRV 19 (North Balwyn)',
  'FS19': 'FRV 19 (North Balwyn)',
  'P67': 'FRV 67 (Ballarat)',
  'FS67': 'FRV 67 (Ballarat)',
  'P68': 'FRV 68 (Lucas)',
  'FS68': 'FRV 68 (Lucas)',
  'P85': 'FRV 85 (Boronia)',
  'FS85': 'FRV 85 (Boronia)',
  'P33': 'FRV 33 (Mentone)',
  'FS33': 'FRV 33 (Mentone)',
  'P09': 'FRV 9 (Somerton)',
  'FS09': 'FRV 9 (Somerton)',
  'P54': 'FRV 54 (Greenvale)',
  'FS54': 'FRV 54 (Greenvale)',
  'P94': 'FRV 94 (Mornington)',
  'FS94': 'FRV 94 (Mornington)',
  'P95': 'FRV 95 (Rosebud)',
  'FS95': 'FRV 95 (Rosebud)',
  'P71': 'FRV 71 (Portland)',
  'FS71': 'FRV 71 (Portland)',
  'P84': 'FRV 84 (South Warrandyte)',
  'FS84': 'FRV 84 (South Warrandyte)',
  'P79': 'FRV 79 (Latrobe West)',
  'FS79': 'FRV 79 (Latrobe West)',
  'P90': 'FRV 90 (Patterson River)',
  'FS90': 'FRV 90 (Patterson River)',

  // CFA Stations
  'BEAC': 'CFA BEACONSFIELD',
  'BERW': 'CFA BERWICK',
  'CURR': 'CFA CURRAWA',
  'SEST': 'CFA SHEPPARTON EAST',
  'DOOK': 'CFA DOOKIE',
  'CHAT': 'CFA CHATSWORTH',
  'SMOR': 'CFA STRATHMORE',
  'BORN': 'CFA BORNES HILL',
  'AVEN': 'CFA AVENEL',
  'TRAR': 'CFA TRARALGON',
  'TRAW': 'CFA TRARALGON WEST',
  'OMEO': 'CFA OMEO',
  'SWCR': 'CFA SWIFT\'S CREEK',
  'BELG': 'CFA BELGRAVE',
  'UPWE': 'CFA UPWEY',
  'DAND': 'CFA DANDENONG',
  'HURS': 'CFA HURSTBRIDGE',
  'WATT': 'CFA WATTLE GLEN',
  'KILM': 'CFA KILMORE',
  'MIDW': 'CFA MIDWAY - OTWAYS',
  'GNAR': 'CFA GNARWARRE',
  'WSEA': 'CFA WINCHELSEA',
  'WURD': 'CFA WURDALE',
  'GTOM': 'CFA GLENTHOMPSON',
  'BMSHBF': 'CFA BACCHUS MARSH Big Fill',
  'MORN': 'CFA MORNINGTON',
  'MTEL': 'CFA MT ELIZA',
  'CARO': 'CFA CAROLINE SPRINGS',
  'ROCK': 'CFA ROCKBANK',
  'KANG': 'CFA KANGAROO GROUND',
  'HOPP': 'CFA HOPPERS CROSSING',
  'WBEE': 'CFA WERRIBEE',
  'MBRK': 'CFA MOOROOLBARK',
  'MONT': 'CFA MONTROSE',
  'CORO': 'CFA CORIO',
  'LARA': 'CFA LARA',
  'HEL331': 'HELITACK 331',
  'HSTG': 'CFA HASTINGS',
  'TYAB': 'CFA TYABB',
  'GBRN': 'CFA GISBORNE',
  'RIDD': 'CFA RIDDELL\'S CREEK',
  'BASS': 'CFA BASS',
  'CORN': 'CFA CORINELLA',
  'KERN': 'CFA KERNOT',
  'COAT': 'CFA COCKATOO',
  'GEMB': 'CFA GEMBROOK',
  'NAWE': 'CFA NARRE WARREN EAST',
  'DROM': 'CFA DROMANA',
  'HAMP': 'CFA HAMPTON PARK',
  'KILC': 'CFA KILCUNDA',
  'NARR': 'CFA NARRE WARREN',
  'NNTH': 'CFA NARRE WARREN NORTH',
  'OFFI': 'CFA OFFICER',
  'PISL': 'CFA PHILLIP ISLAND',
  'ROSE': 'CFA ROSEBUD',
  'SEMO': 'CFA SAN REMO',
  'CADW': 'CFA CARRUM DOWNS',
  'SIMP': 'CFA SIMPSON',
  'HGAP': 'CFA HALLS GAP',
  'MOYS': 'CFA MOYSTON',
  'POMO': 'CFA POMONAL',
  'TRUG': 'CFA TRUGANINA',
  'KIRK': 'CFA KIRKSTALL',
  'KORO': 'CFA KOROIT',
  'WINS': 'CFA WINSLOW & YARPTURK',
  'PANT': 'CFA PANTON HILL',
  'WARR': 'CFA WARRANDYTE',
  'MACE': 'CFA MACEDON',
  'MTMC': 'CFA MOUNT MACEDON',
  'WOOD': 'CFA WOODEND',
  'AXEC': 'CFA AXE CREEK',
  'JUNO': 'CFA JUNORTOUN',
  'SAYE': 'CFA STRATHFIELDSAYE',
  'NARN': 'CFA NAR NAR GOON',
  'NARNT1': 'CFA NAR NAR GOON',
  'PKHM': 'CFA PAKENHAM',
  'TOOM': 'CFA TOOMUC',
  'BELMT1': 'CFA BELMONT',
  'BELM': 'CFA BELMONT',
  'PTCO': 'CFA POINT COOK',
  'BRIA': 'CFA BRIAGOLONG',
  'VALE': 'CFA VALENCIA CREEK',
  'BARA': 'CFA BALLARAT',
  'WENO': 'CFA WENDOUREE',
  'WENOT1': 'CFA WENDOUREE',
  'BIRC': 'CFA BIRCHIP',
  'PAYN': 'CFA PAYNESVILLE',
  'NAPO': 'CFA NAPOLEONS-ENFIELD',
  'SEBA': 'CFA SEBASTOPOL',
  'SMYT': 'CFA SMYTHESDALE',
  'CMUT': 'CFA CARAMUT',
  'LINT': 'CFA LINTON',
  'HANB': 'CFA HANCOCK BALLARAT',
  'DIAM': 'CFA DIAMOND CREEK',
  'PLEN': 'CFA PLENTY',
  'WAND': 'CFA WANDIN',
  'BUNI': 'CFA BUNINYONG',
  'BALA': 'CFA BALLAN',
  'WOLL': 'CFA WOLLERT & DISTRICT',
  'CBRK': 'CFA CRAIGIEBURN',
  'BRM': 'CFA CRAIGIEBURN',
  'KAKA': 'CFA KAL KALLO',
  'ELAI': 'CFA ELAINE',
  'ELAIT1': 'CFA ELAINE',
  'SKYE': 'CFA SKYE',
  'EPPI': 'CFA EPPING',
  'LEON': 'CFA LEONGATHA',
  'GREE': 'CFA GREENVALE',
  'BULL': 'CFA BULLA',
  'BULLT1': 'CFA BULLA',
  'BULLT2': 'CFA BULLA',
  'BLCK': 'CFA BERRIWILLOCK',
  'CULG': 'CFA CULGOA',
  'LALB': 'CFA LALBERT',
  'HELI331': 'HELIATTACK 331',
  'BOM356': 'Bomber 356',
  'BRATT1': 'CFA BALLARAT CITY',
  'BRATT2': 'CFA BALLARAT CITY',
  'SMET': 'CFA SMEATON',
  'SMETT1': 'CFA SMEATON',
  'GLPK': 'CFA GLEN PARK',
  'CWIC': 'CFA CRESWICK',
  'LENT': 'CFA LAKES ENTRANCE',
  'NWIL': 'CFA NULLAWIL',
  'NWILT1': 'CFA NULLAWIL',
  'ULTI': 'CFA ULTIMA',
  'ULTIT1': 'CFA ULTIMA',
  'WYCH': 'CFA WYCHEPROOF',
  'JHNS': 'CFA BUMBERRAH',
  'JHNST1': 'CFA BUMBERRAH',
  'METU': 'CFA METUNG',
  'BDAL': 'CFA BAIRNSDALE',
  'SARS': 'CFA SARSFIELD',
  'SARST1': 'CFA SARSFIELD',
  'BDALT1': 'CFA BAIRNSDALE',
  'BRUT': 'CFA BRUTHEN',
  'ROWV': 'CFA ROWVILLE',
  'SCOR': 'CFA SCORESBY',
  'COOM': 'CFA COOMA',
  'GIRG': 'CFA GIRGARRE',
  'STPE': 'CFA STANHOPE',
  'HALL': 'CFA HALLAM',
  'FRES': 'CFA FRESHWATER CREEK',
  'GROV': 'CFA GROVEDALE',
  'FREST2': 'CFA FRESHWATER CREEK',
  'MODE': 'CFA MODEWARRE',
  'MODET1': 'CFA MODEWARRE',
  'MERY': 'CFA MYRNIONG',
  'MTON': 'CFA MELTON',
  'TIMM': 'CFA TIMMERING'
};

export function getStationName(code: string): string {
  // Remove brackets and underscore if present
  const cleanCode = code.replace(/[\[\]_]/g, '');
  
  // Handle P-prefixed codes by checking both P and FS versions
  if (cleanCode.startsWith('P')) {
    return STATION_NAMES[cleanCode] || STATION_NAMES[`FS${cleanCode.slice(1)}`] || code;
  }

  // Handle tanker codes (T1, T2, etc.)
  const tankerMatch = cleanCode.match(/^([A-Z]{4})T[1-9]$/);
  if (tankerMatch) {
    const baseCode = tankerMatch[1];
    const baseName = STATION_NAMES[baseCode];
    if (baseName) {
      return `${baseName} ${cleanCode.slice(4)}`; // Append T1, T2, etc.
    }
  }
  
  return STATION_NAMES[cleanCode] || code;
}

export function formatStationCode(code: string): string {
  return code.replace(/[\[\]_]/g, '');
}