// Map of station codes to full names
export const STATION_NAMES: Record<string, string> = {
  // Specialized FRV Units
  'R3': 'FRV Rescue Carlton',
  'TB10': 'FRV Teleboom Richmond',
  'BA38': 'FRV BA Support South Melbourne',
  'HZ88': 'FRV Hazmat Hallam',
  'PT14': 'FRV Pumper Tanker Bundoora',
  'LP87': 'FRV Ladder Platform Dandenong',
  'PT9': 'FRV Pumper Tanker Somerton',
  'PT31': 'FRV Pumper Tanker Glen Waverley',
  'BA1': 'FRV BA Support Eastern Hill',
  'PH1': 'FRV Platform Hydraulic Eastern Hill',
  'R1': 'FRV Rescue Eastern Hill',
  'R2': 'FRV Rescue West Melbourne',
  'R38': 'FRV Rescue South Melbourne',
  'R87': 'FRV Rescue Dandenong',
  'HZ1': 'FRV Hazmat Eastern Hill',
  'TB38': 'FRV Teleboom South Melbourne',
  'TB87': 'FRV Teleboom Dandenong',
  'LP1': 'FRV Ladder Platform Eastern Hill',
  'LP38': 'FRV Ladder Platform South Melbourne',

  // FRV Stations - P prefix
  'P01': 'FRV 1 (Eastern Hill)',
  'P02': 'FRV 2 (West Melbourne)',
  'P03': 'FRV 3 (Carlton)',
  'P04': 'FRV 4 (Brunswick)',
  'P05': 'FRV 5 (Broadmeadows)',
  'P06': 'FRV 6 (Pascoe Vale)',
  'P07': 'FRV 7 (Thomastown)',
  'P09': 'FRV 9 (Somerton)',
  'P10': 'FRV 10 (Richmond)',
  'P11': 'FRV 11 (Epping)',
  'P12': 'FRV 12 (Preston)',
  'P13': 'FRV 13 (Northcote)',
  'P14': 'FRV 14 (Bundoora)',
  'P15': 'FRV 15 (Heidelberg)',
  'P16': 'FRV 16 (Greensborough)',
  'P18': 'FRV 18 (Hawthorn)',
  'P19': 'FRV 19 (North Balwyn)',
  'P20': 'FRV 20 (Box Hill)',
  'P22': 'FRV 22 (Ringwood)',
  'P23': 'FRV 23 (Burwood)',
  'P24': 'FRV 24 (Glen Iris)',
  'P25': 'FRV 25 (Oakleigh)',
  'P26': 'FRV 26 (Croydon)',
  'P27': 'FRV 27 (Nunawading)',
  'P28': 'FRV 28 (Vermont South)',
  'P29': 'FRV 29 (Clayton)',
  'P30': 'FRV 30 (Templestowe)',
  'P31': 'FRV 31 (Glen Waverley)',
  'P32': 'FRV 32 (Ormond)',
  'P33': 'FRV 33 (Mentone)',
  'P34': 'FRV 34 (Highett)',
  'P35': 'FRV 35 (Windsor)',
  'P38': 'FRV 38 (South Melbourne)',
  'P39': 'FRV 39 (Port Melbourne)',
  'P40': 'FRV 40 (Laverton)',
  'P41': 'FRV 41 (St Albans)',
  'P42': 'FRV 42 (Newport)',
  'P43': 'FRV 43 (Deer Park)',
  'P44': 'FRV 44 (Sunshine)',
  'P45': 'FRV 45 (Brooklyn)',
  'P46': 'FRV 46 (Altona)',
  'P47': 'FRV 47 (Footscray)',
  'P48': 'FRV 48 (Taylors Lakes)',
  'P51': 'FRV 51 (Keilor)',
  'P52': 'FRV 52 (Tullamarine)',
  'P53': 'FRV 53 (Sunbury)',
  'P54': 'FRV 54 (Greenvale)',
  'P55': 'FRV 55 (Caroline Springs)',
  'P56': 'FRV 56 (Melton)',
  'P57': 'FRV 57 (Tarneit)',
  'P58': 'FRV 58 (Point Cook)',
  'P59': 'FRV 59 (Derrimut)',
  'P61': 'FRV 61 (Lara)',
  'P62': 'FRV 62 (Corio)',
  'P63': 'FRV 63 (Geelong)',
  'P63B': 'FRV 63B (Geelong)',
  'P64': 'FRV 64 (Belmont)',
  'P66': 'FRV 66 (Ocean Grove)',
  'P67': 'FRV 67 (Ballarat)',
  'P67B': 'FRV 67B (Ballarat)',
  'P68': 'FRV 68 (Lucas)',
  'P70': 'FRV 70 (Warrnambool)',
  'P71': 'FRV 71 (Portland)',
  'P72': 'FRV 72 (Mildura)',
  'P73': 'FRV 73 (Bendigo)',
  'P74': 'FRV 74 (Wangaratta)',
  'P75': 'FRV 75 (Shepparton)',
  'P76': 'FRV 76 (Wodonga)',
  'P77': 'FRV 77 (Traralgon)',
  'P78': 'FRV 78 (Morwell)',
  'P79': 'FRV 79 (Latrobe West)',
  'P80': 'FRV 80 (Craigieburn)',
  'P81': 'FRV 81 (South Morang)',
  'P82': 'FRV 82 (Eltham)',
  'P84': 'FRV 84 (South Warrandyte)',
  'P85': 'FRV 85 (Boronia)',
  'P86': 'FRV 86 (Rowville)',
  'P87': 'FRV 87 (Dandenong)',
  'P88': 'FRV 88 (Hallam)',
  'P89': 'FRV 89 (Springvale)',
  'P90': 'FRV 90 (Patterson River)',
  'P91': 'FRV 91 (Frankston)',
  'P92': 'FRV 92 (Cranbourne)',
  'P93': 'FRV 93 (Pakenham)',
  'P94': 'FRV 94 (Mornington)',
  'P95': 'FRV 95 (Rosebud)',

  // FRV Stations - FS prefix
  'FS01': 'FRV 1 (Eastern Hill)',
  'FS02': 'FRV 2 (West Melbourne)',
  'FS03': 'FRV 3 (Carlton)',
  'FS04': 'FRV 4 (Brunswick)',
  'FS05': 'FRV 5 (Broadmeadows)',
  'FS06': 'FRV 6 (Pascoe Vale)',
  'FS07': 'FRV 7 (Thomastown)',
  'FS09': 'FRV 9 (Somerton)',
  'FS10': 'FRV 10 (Richmond)',
  'FS11': 'FRV 11 (Epping)',
  'FS12': 'FRV 12 (Preston)',
  'FS13': 'FRV 13 (Northcote)',
  'FS14': 'FRV 14 (Bundoora)',
  'FS15': 'FRV 15 (Heidelberg)',
  'FS16': 'FRV 16 (Greensborough)',
  'FS18': 'FRV 18 (Hawthorn)',
  'FS19': 'FRV 19 (North Balwyn)',
  'FS20': 'FRV 20 (Box Hill)',
  'FS22': 'FRV 22 (Ringwood)',
  'FS23': 'FRV 23 (Burwood)',
  'FS24': 'FRV 24 (Glen Iris)',
  'FS25': 'FRV 25 (Oakleigh)',
  'FS26': 'FRV 26 (Croydon)',
  'FS27': 'FRV 27 (Nunawading)',
  'FS28': 'FRV 28 (Vermont South)',
  'FS29': 'FRV 29 (Clayton)',
  'FS30': 'FRV 30 (Templestowe)',
  'FS31': 'FRV 31 (Glen Waverley)',
  'FS32': 'FRV 32 (Ormond)',
  'FS33': 'FRV 33 (Mentone)',
  'FS34': 'FRV 34 (Highett)',
  'FS35': 'FRV 35 (Windsor)',
  'FS38': 'FRV 38 (South Melbourne)',
  'FS39': 'FRV 39 (Port Melbourne)',
  'FS40': 'FRV 40 (Laverton)',
  'FS41': 'FRV 41 (St Albans)',
  'FS42': 'FRV 42 (Newport)',
  'FS43': 'FRV 43 (Deer Park)',
  'FS44': 'FRV 44 (Sunshine)',
  'FS45': 'FRV 45 (Brooklyn)',
  'FS46': 'FRV 46 (Altona)',
  'FS47': 'FRV 47 (Footscray)',
  'FS48': 'FRV 48 (Taylors Lakes)',
  'FS51': 'FRV 51 (Keilor)',
  'FS52': 'FRV 52 (Tullamarine)',
  'FS53': 'FRV 53 (Sunbury)',
  'FS54': 'FRV 54 (Greenvale)',
  'FS55': 'FRV 55 (Caroline Springs)',
  'FS56': 'FRV 56 (Melton)',
  'FS57': 'FRV 57 (Tarneit)',
  'FS58': 'FRV 58 (Point Cook)',
  'FS59': 'FRV 59 (Derrimut)',
  'FS61': 'FRV 61 (Lara)',
  'FS62': 'FRV 62 (Corio)',
  'FS63': 'FRV 63 (Geelong)',
  'FS63B': 'FRV 63B (Geelong)',
  'FS64': 'FRV 64 (Belmont)',
  'FS66': 'FRV 66 (Ocean Grove)',
  'FS67': 'FRV 67 (Ballarat)',
  'FS67B': 'FRV 67B (Ballarat)',
  'FS68': 'FRV 68 (Lucas)',
  'FS70': 'FRV 70 (Warrnambool)',
  'FS71': 'FRV 71 (Portland)',
  'FS72': 'FRV 72 (Mildura)',
  'FS73': 'FRV 73 (Bendigo)',
  'FS74': 'FRV 74 (Wangaratta)',
  'FS75': 'FRV 75 (Shepparton)',
  'FS76': 'FRV 76 (Wodonga)',
  'FS77': 'FRV 77 (Traralgon)',
  'FS78': 'FRV 78 (Morwell)',
  'FS79': 'FRV 79 (Latrobe West)',
  'FS80': 'FRV 80 (Craigieburn)',
  'FS81': 'FRV 81 (South Morang)',
  'FS82': 'FRV 82 (Eltham)',
  'FS84': 'FRV 84 (South Warrandyte)',
  'FS85': 'FRV 85 (Boronia)',
  'FS86': 'FRV 86 (Rowville)',
  'FS87': 'FRV 87 (Dandenong)',
  'FS88': 'FRV 88 (Hallam)',
  'FS89': 'FRV 89 (Springvale)',
  'FS90': 'FRV 90 (Patterson River)',
  'FS91': 'FRV 91 (Frankston)',
  'FS92': 'FRV 92 (Cranbourne)',
  'FS93': 'FRV 93 (Pakenham)',
  'FS94': 'FRV 94 (Mornington)',
  'FS95': 'FRV 95 (Rosebud)',

  // CFA Stations
  'TOOM': 'CFA TOOMUC',
  'CADW': 'CFA CARRUM DOWNS',
  'ARAU': 'CFA ARARAT',
  'DORE': 'CFA DOREEN',
  'MERN': 'CFA MERNDA',
  'HADD': 'CFA HADDON',
  'CARL': 'CFA CARLSRUHE',
  'KYNE': 'CFA KYNETON',
  'NEWH': 'CFA NEWHAM',
  'MALM': 'CFA MALMSBURY',
  'PAST': 'CFA PASTORIA',
  'TYLD': 'CFA TYLDEN',
  'GMER': 'CFA GLENROY & MERRIJIG',
  'MANU': 'CFA MANSFIELD',
  'KOOW': 'CFA KOO WEE RUP',
  'LANG': 'CFA LANG LANG',
  'WONG': 'CFA WONGA PARK',
  'STHW': 'CFA SOUTH WARRANDYTE',
  'DARR': 'CFA DARRAWEIT GUIM',
  'BOLI': 'CFA BOLINDA & MONEGETTA',
  'CBRN': 'CFA CRAIGIEBURN',
  'WALN': 'CFA WALLINGTON',
  'LEOP': 'CFA LEOPOLD',
  'DRYS': 'CFA DRYSDALE',
  'HAMP': 'CFA HAMPTON PARK',
  'PTCO': 'CFA POINT COOK',
  'MONB': 'CFA MONBULK',
  'BARW': 'CFA BARWON HEADS',
  'STAR': 'CFA ST ARNAUD',
  'WALL': 'CFA WALLAN',
  'WANG': 'CFA WANDONG',
  'SHGP': 'CFA Seymour GROUP',
  'BMSH': 'CFA BACCHUS MARSH',
  'YGON': 'CFA YARRAGON',
  'KAKA': 'CFA KAL KALLO',
  'MACC': 'CFA MACCLESFIELD',
  'TIGP': 'CFA Timboon GROUP',
  'KALL': 'CFA KALLISTA-THE PATCH',
  'PEAR': 'CFA PEARCEDALE',
  'SARS': 'CFA SARSFIELD',
  'DAND': 'CFA DANDENONG',
  'DROU': 'CFA DROUIN',
  'BELG': 'CFA BELGRAVE',
  'UPWE': 'CFA UPWEY',
  'GPGP': 'CFA Grampians GROUP',
  'WATT': 'CFA WATTLE GLEN',
  'HURS': 'CFA HURSTBRIDGE',
  'BARM': 'CFA BARMAH',
  'EHAM': 'CFA ELTHAM',
  'DIAM': 'CFA DIAMOND CREEK',
  'COLA': 'CFA COLAC',
  'SEYM': 'CFA SEYMOUR',
  'NNTH': 'CFA NARRE WARREN NORTH',
  'SILV': 'CFA SILVAN',
  'COIM': 'CFA COIMADAI',
  'CAGP': 'CFA Camperdown GROUP',
  'MBRK': 'CFA MOOROOLBARK',
  'YELL': 'CFA YELLINGBO',
  'PKHM': 'CFA PAKENHAM',
  'COAT': 'CFA COCKATOO',
  'MARY': 'CFA MARYKNOLL & DISTRICT',
  'PAKU': 'CFA PAKENHAM UPPER',
  'BEUP': 'CFA BEACONSFIELD UPPER',
  'BEAC': 'CFA BEACONSFIELD',
  'BAYL': 'CFA BAYLES',
  'TYNO': 'CFA TYNONG',
  'BUNY': 'CFA BUNYIP',
  'MTON': 'CFA MELTON',
  'GBRN': 'CFA GISBORNE',
  'RIDD': 'CFA RIDDELL\'S CREEK',
  'DAYL': 'CFA DAYLESFORD',
  'WAND': 'CFA WANDIN',
  'GRUY': 'CFA GRUYERE',
  'SEVI': 'CFA SEVILLE',
  'MTEV': 'CFA MT EVELYN',
  'COLD': 'CFA COLDSTREAM',
  'LARA': 'CFA LARA',
  'CORO': 'CFA CORIO',
  'GGRY': 'CFA GLENGARRY',
  'SELB': 'CFA SELBY',
  'TYAB': 'CFA TYABB',
  'HSTG': 'CFA HASTINGS',
  'SNBY': 'CFA SUNBURY',
  'HAMI': 'CFA HAMILTON',
  'ELAI': 'CFA ELAINE',
  'DIGG': 'CFA DIGGERS REST',
  'MTMC': 'CFA MOUNT MACEDON',
  'HANB': 'CFA HANCOCK BALLARAT',
  'MACE': 'CFA MACEDON',
  'HUNL': 'CFA HUNTLY',
  'WOOD': 'CFA WOODEND',
  'WBOL': 'CFA WARRNAMBOOL',
  'CORN': 'CFA CORINELLA',
  'BASS': 'CFA BASS',
  'KERN': 'CFA KERNOT',
  'ROWS': 'CFA ROWSLEY',
  'MORR': 'CFA MORRISONS & DISTRICT',
  'GORD': 'CFA GORDON',
  'LEGP': 'CFA Leigh GROUP',
  'CHIR': 'CFA Chirnside Park',
  'WENO': 'CFA WENDOUREE',
  'MEGE': 'CFA MT EGERTON',
  'WALA': 'CFA WALLACE',
  'MTWA': 'CFA MT WALLACE',
  'MBOK': 'CFA MILLBROOK',
  'GEMB': 'CFA GEMBROOK',
  'SRGP': 'CFA Sunraysia GROUP',
  'NAWE': 'CFA NARRE WARREN EAST',
  'MINU': 'CFA MINYIP',
  'BELS': 'CFA BELGRAVE HEIGHTS & SOUTH',
  'MORW': 'CFA MORWELL',
  'KANG': 'CFA KANGAROO GROUND',
  'MYGP': 'CFA Mid Murray GROUP',
  'MARO': 'CFA MAROONA',
  'GUND': 'CFA GUNDOWRING',
  'MILD': 'CFA MILDURA',
  'LWGP': 'CFA Lowan GROUP',
  'NHTN': 'CFA NORTH HAMILTON',
  'DIXO': 'CFA DIXONS CREEK',
  'GRED': 'CFA GREENDALE',
  'BLAC': 'CFA BLACKWOOD',
  'HESK': 'CFA HESKET-KERRIE',
  'NARN': 'CFA NAR NAR GOON',
  'BALA': 'CFA BALLAN',
  'SLAT': 'CFA SLATY CREEK',
  'MYRN': 'CFA MYRNIONG',
  'MERE': 'CFA MEREDITH',
  'MENZ': 'CFA MENZIES CREEK',
  'CAMP': 'CFA CAMPBELLS CREEK',
  'MALD': 'CFA MALDON',
  'CHEW': 'CFA CHEWTON',
  'HARC': 'CFA HARCOURT',
  'CMAI': 'CFA CASTLEMAINE',
  'TARA': 'CFA TARADALE',
  'RUPR': 'CFA RUPANYUP',
  'MARN': 'CFA MARNOO',
  'RICH': 'CFA RICH AVON',
  'NOBL': 'CFA NOBLE PARK',
  'WHNU': 'CFA WUNGHNU',
  'NRNG': 'CFA NARING',
  'INGL': 'CFA INGLEWOOD',
  'FENT': 'CFA FENTONS CREEK',
  'RHEO': 'CFA RHEOLA',
  'WEDR': 'CFA WEDDERBURN',
  'PAYN': 'CFA PAYNESVILLE',
  'BERR': 'CFA BERRIMAL',
  'ARTH': 'CFA ARTHURS CREEK',
  'NKAH': 'CFA NUMURKAH',
  'KATU': 'CFA KATUNGA',
  'QUEE': 'CFA QUEENSCLIFF',
  'MANN': 'CFA MANNERIM',
  'STLE': 'CFA ST LEONARDS-INDENTED HEAD',
  'TOOR': 'CFA TOORADIN',
  'HIGH': 'CFA HIGHTON',
  'HDGP': 'CFA Hawkesdale GROUP',
  'TEGP': 'CFA East Loddon GROUP',
  'WDGP': 'CFA Wedderburn GROUP',
  'LSGP': 'CFA Gordon GROUP',
  'MONT': 'CFA MONTROSE',
  'OCEA': 'CFA OCEAN GROVE',
  'LENT': 'CFA LAKES ENTRANCE',
  'HALL': 'CFA HALLAM',
  'BERW': 'CFA BERWICK',
  'MILW': 'CFA MILAWA',
  'NEWB': 'CFA NEWBOROUGH',
  'ROCK': 'CFA ROCKBANK',
  'WARB': 'CFA WARBURTON',
  'STPE': 'CFA STANHOPE',
  'MDRG': 'CFA MANDURANG',
  'YEAA': 'CFA YEA',
  'WBEE': 'CFA WERRIBEE',
  'REDC': 'CFA RED CLIFFS',
  'PARW': 'CFA PARWAN',
  'NAPO': 'CFA NAPOLEONS-ENFIELD',
  'SRAT': 'CFA SOUTH WANGARATTA',
  'RUBY': 'CFA RUBY',
  'TGAL': 'CFA TONGALA',
  'WRAT': 'CFA WANGARATTA',
  'KORU': 'CFA KORUMBURRA',
  'BELM': 'CFA BELMONT',
  'LANW': 'CFA LANGWARRIN',
  'LEVA': 'CFA LENEVA',
  'MNTH': 'CFA MIRBOO NORTH',
  'GOLD': 'CFA GOLDEN SQUARE',
  'TOOL': 'CFA TOOLERN VALE',
  'HVIL': 'CFA HEALESVILLE',
  'NATH': 'CFA NATHALIA',
  'HAWK': 'CFA HAWKESDALE',
  'MOYS': 'CFA MOYSTON',
  'ANGP': 'CFA Anakie GROUP',
  'WGGP': 'CFA Wangaratta GROUP',
  'TREN': 'CFA TRENTHAM',
  'BOOL': 'CFA BOOLARRA',
  'HALO': 'CFA HALLORA',
  'GDGP': 'CFA Tullaroop GROUP',
  'BEND': 'CFA BENDIGO',
  'JUNO': 'CFA JUNORTOUN',
  'BARA': 'CFA BALLARAT',
  'DARN': 'CFA DARNUM & ELLINBANK',
  'GIRG': 'CFA GIRGARRE',
  'EPGP': 'CFA Bendigo GROUP',
  'SCOR': 'CFA SCORESBY',
  'BAYS': 'CFA BAYSWATER',
  'BORO': 'CFA BORONIA',
  'HEAT': 'CFA HEATH HILL - YANNATHAN',
  'OFFI': 'CFA OFFICER',
  'SMYT': 'CFA SMYTHESDALE',
  'RYEA': 'CFA RYE',
  'HWOD': 'CFA HAZELWOOD NORTH',
  'CHUR': 'CFA CHURCHILL',
  'KILM': 'CFA KILMORE',
  'MRST': 'CFA MINERS REST',
  'ROSR': 'CFA ROSEDALE',
  'LFRD': 'CFA LONGFORD',
  'SALE': 'CFA SALE',
  'BRFD': 'CFA BROADFORD',
  'HOPP': 'CFA HOPPERS CROSSING',
  'SVAL': 'CFA SPRINGVALE',
  'SEST': 'CFA SHEPPARTON EAST',
  'SHEP': 'CFA SHEPPARTON',
  'MPNA': 'CFA MOOROOPNA',
  'EDIT': 'CFA EDITHVALE',
  'PLEN': 'CFA PLENTY',
  'GREE': 'CFA GREENVALE',
  'WSTO': 'CFA WOODSTOCK WEST',
  'TARN': 'CFA TARNAGULLA',
  'PETE': 'CFA PETERBOROUGH',
  'NIRR': 'CFA NIRRANDA SOUTH',
  'LHEY': 'CFA LOWER HEYTESBURY',
  'DROM': 'CFA DROMANA',
  'MORO': 'CFA MOOROODUC',
  'YARR': 'CFA YARRAMBAT',
  'KYAB': 'CFA KYABRAM',
  'STRU': 'CFA STRATFORD',
  'CBNK': 'CFA CLYDEBANK',
  'AVEN': 'CFA AVENEL',
  'SKYE': 'CFA SKYE',
  'FERN': 'CFA FERNTREE GULLY',
  'MSGP': 'CFA Mount Rouse GROUP',
  'SHEL': 'CFA SHELFORD',
  'MLGP': 'CFA Mortlake GROUP',
  'ECHU': 'CFA ECHUCA',
  'LURG': 'CFA LURG',
  'BENU': 'CFA BENALLA',
  'WGAT': 'CFA WHITEGATE',
  'PORT': 'CFA PORTARLINGTON',
  'LOCK': 'CFA LOCKWOOD',
  'COBR': 'CFA COBRAM',
  'BONE': 'CFA BONEO',
  'BUNI': 'CFA BUNINYONG',
  'ROSE': 'CFA ROSEBUD',
  'RESE': 'CFA RESEARCH',
  'DERE': 'CFA DEREEL',
  'SWAU': 'CFA SWAN HILL',
  'KERA': 'CFA KERANG',
  'GNGP': 'CFA Kerang GROUP',
  'MORN': 'CFA MORNINGTON',
  'ERIC': 'CFA ERICA & DISTRICT',
  'MIAM': 'CFA MIA MIA',
  'KOTU': 'CFA KOTUPNA',
  'PYAL': 'CFA PYALONG',
  'PRTF': 'CFA PORT FAIRY',
  'TATU': 'CFA TATURA',
  'NWMO': 'CFA NW MOOROOPNA',
  'MGUM': 'CFA MERRIGUM',
  'WYUN': 'CFA WYUNA',
  'CONN': 'CFA CONNEWARRE',
  'UNDE': 'CFA UNDERA',
  'MTMA': 'CFA MT MARTHA',
  'HORS': 'CFA HORSHAM',
  'WURD': 'CFA WURDALE',
  'MOYH': 'CFA MOYHU',
  'YULE': 'CFA YULECART',
  'SWEU': 'CFA STAWELL',
  'ADRA': 'CFA ALEXANDRA',
  'ELDO': 'CFA ELDORADO',
  'CHRI': 'CFA CHRISTMAS HILLS',
  'MTBU': 'CFA MT BUNINYONG',
  'AKDC': 'CFA AKD-CALCO',
  'KORO': 'CFA KOROIT',
  'STHM': 'CFA SOUTH MORANG',
  'MOEE': 'CFA MOE',
  'KEYS': 'CFA KEYSBOROUGH',
  'MAUD': 'CFA MAUDE',
  'THEB': 'CFA THE BASIN',
  'COOM': 'CFA COOMA',
  'BITT': 'CFA BITTERN',
  'CRIB': 'CFA CRIB POINT',
  'TRUG': 'CFA TRUGANINA',
  'EURO': 'CFA EUROA',
  'COLE': 'CFA COLERAINE',
  'LOCH': 'CFA LOCH',
  'HILC': 'CFA HILLCREST',
  'BOOR': 'CFA BOORCAN',
  'BOOK': 'CFA BOOKAAR',
  'MAFF': 'CFA MAFFRA',
  'NADI': 'CFA NATIMUK & DISTRICT',
  'KOLO': 'CFA KOLORA',
  'WING': 'CFA WINGEEL',
  'MIDW': 'CFA MIDWAY - OTWAYS',
  'TERA': 'CFA TERANG',
  'DIXI': 'CFA TERANG-DIXIE',
  'NOOR': 'CFA NOORAT & DISTRICT',
  'NOOJ': 'CFA NOOJEE',
  'HEYW': 'CFA HEYWOOD',
  'STAN': 'CFA ST ANDREWS',
  'NARR': 'CFA NARRE WARREN',
  'PANT': 'CFA PANTON HILL',
  'WOLL': 'CFA WOLLERT & DISTRICT',
  'EPPI': 'CFA EPPING',
  'WRAK': 'CFA WARRAK',
  'ANGL': 'CFA ANGLESEA',
  'TRQY': 'CFA TORQUAY',
  'MODE': 'CFA MODEWARRE',
  'NSTH': 'CFA NEERIM SOUTH',
  'TATO': 'CFA TATONG',
  'MOLY': 'CFA MOLYULLAH',
  'MNRO': 'CFA MUNRO',
  'WWST': 'CFA WODONGA WEST',
  'NITH': 'CFA NILMA NORTH',
  'BWTR': 'CFA BROADWATER',
  'LARP': 'CFA LARPENT',
  'NALA': 'CFA NALANGIL',
  'WAOG': 'CFA WARRONG',
  'TLNG': 'CFA TOOLONG',
  'KIRK': 'CFA KIRKSTALL',
  'THNA': 'CFA THOONA',
  'WBEL': 'CFA WARRACKNABEAL',
  'DONA': 'CFA DONALD',
  'KSTN': 'CFA KINGSTON',
  'BOST': 'CFA BOSTOCKS CREEK',
  'TRIP': 'CFA TERIP TERIP',
  'BMCK': 'CFA BUANGOR & MIDDLE CREEK',
  'COBD': 'CFA COBDEN',
  'CDWN': 'CFA CAMPERDOWN',
  'TALB': 'CFA TALBOT',
  'MAGH': 'CFA MARYBOROUGH',
  'LEON': 'CFA LEONGATHA',
  'HGAP': 'CFA HALLS GAP',
  'SOVL': 'CFA SOMERVILLE',
  'CBRK': 'CFA CARISBROOK',
  'ELPH': 'CFA ELPHINSTONE',
  'STRN': 'CFA STRATHMERTON',
  'BEXT': 'CFA BAMAWM EXTENSION',
  'EVIL': 'CFA DEAKIN NORTH WEST',
  'WEME': 'CFA WEMEN',
  'LRNE': 'CFA LORNE',
  'BBND': 'CFA BOUNDARY BEND',
  'ROBI': 'CFA ROBINVALE',
  'DUMB': 'CFA DUMBALK',
  'BIRR': 'CFA BIRREGURRA',
  'NARB': 'CFA NARBETHONG',
  'CRAN': 'CFA CRANBOURNE',
  'FTON': 'CFA FRANKSTON',
  'GRID': 'CFA GRAND RIDGE PLANTATIONS',
  'TYER': 'CFA TYERS',
  'PISL': 'CFA PHILLIP ISLAND',
  'INVE': 'CFA INVERLEIGH',
  'WBRY': 'CFA WESTBURY',
  'WGRO': 'CFA WILLOWGROVE',
  'TWOL': 'CFA TRAWOOL',
  'LSMR': 'CFA LISMORE',
  'STON': 'CFA STONEHAVEN',
  'SEBA': 'CFA SEBASTOPOL',
  'BARO': 'CFA BARONGAROOK WEST',
  'LLOG': 'CFA LANGI LOGAN',
  'GRRN': 'CFA GREAT WESTERN',
  'PIMP': 'CFA PIMPINIO',
  'WARA': 'CFA WARRAGUL',
  'DOOE': 'CFA DOOEN',
  'IMAY': 'CFA INVERMAY',
  'WODO': 'CFA WODONGA',
  'VTWN': 'CFA VIOLET TOWN',
  'BOHO': 'CFA BOHO',
  'TRAR': 'CFA TRARALGON',
  'TRAE': 'CFA TRARALGON EAST',
  'SOME': 'CFA SOMERS',
  'BALN': 'CFA BALNARRING',
  'PATR': 'CFA PATTERSON RIVER',
  'DWST': 'CFA DROUIN WEST',
  'SFLD': 'CFA SPRINGFIELD',
  'BREE': 'CFA BUNGAREE',
  'WIGP': 'CFA Winchelsea GROUP',
  'GROV': 'CFA GROVEDALE',
  'GEWE': 'CFA GEELONG WEST',
  'WHIT': 'CFA WHITTLESEA',
  'WBRN': 'CFA WESBURN-MILLGROVE',
  'LIND': 'CFA LINDENOW SOUTH',
  'EMLD': 'CFA EMERALD',
  'IRYM': 'CFA IRYMPLE',
  'METU': 'CFA METUNG',
  'BBRN': 'CFA BANNOCKBURN',
  'WARR': 'CFA WARRANDYTE',
  'LOVE': 'CFA LOVELY BANKS',
  'BEGP': 'CFA Bellarine GROUP',
  'MAGP': 'CFA Maroondah GROUP',
  'WRAP': 'CFA WERRAP',
  'KIAL': 'CFA KIALLA & DISTRICT',
  'YVGP': 'CFA Yarra Valley GROUP',
  'RAIU': 'CFA RAINBOW',
  'DKGP': 'CFA Deakin GROUP',
  'CRKE': 'CFA COROROOKE',
  'HOPU': 'CFA HOPETOUN',
  'UPPE': 'CFA UPPER FERNTREE GULLY',
  'ROWV': 'CFA ROWVILLE',
  'HWES': 'CFA HOPETOUN WEST',
  'YAAP': 'CFA YAAPEET',
  'SASS': 'CFA SASSAFRAS & FERNY CREEK',
  'DARG': 'CFA DARGO',
  'RAGL': 'CFA RAGLAN',
  'TADI': 'CFA TARRAWINGEE & DISTRICT',
  'YACR': 'CFA YACKANDANDAH',
  'LETH': 'CFA LETHBRIDGE',
  'ANAK': 'CFA ANAKIE',
  'CLYD': 'CFA CLYDE',
  'TOOB': 'CFA TOOBORAC',
  'DEAN': 'CFA DEANS MARSH',
  'OTWY': 'CFA OTWAY',
  'LOWD': 'CFA LONGWOOD',
  'BAWA': 'CFA BARNAWARTHA',
  'THDL': 'CFA THORPDALE',
  'YYAH': 'CFA YARROWEYAH',
  'YALC': 'CFA YALCA & YIELIMA',
  'PNGP': 'CFA Bacchus Marsh GROUP',
  'WAAI': 'CFA WAAIA',
  'GLDA': 'CFA GLENALADALE',
  'MZGP': 'CFA Morwell GROUP',
  'BRIA': 'CFA BRIAGOLONG',
  'FLOW': 'CFA FLOWERDALE',
  'DEVO': 'CFA DEVON MEADOWS',
  'KFLT': 'CFA KANGAROO FLAT',
  'BAXT': 'CFA BAXTER',
  'BADG': 'CFA BADGER CREEK',
  'CHIU': 'CFA CHILTERN',
  'WBBG': 'CFA WAREEK & BUNG BONG',
  'AMPH': 'CFA AMPHITHEATRE',
  'AVOU': 'CFA AVOCA',
  'WARD': 'CFA WARRENMANG & DISTRICT',
  'NYLK': 'CFA NATTE YALLOCK',
  'MURC': 'CFA MURCHISON',
  'BDIS': 'CFA BOOROOLITE & DISTRICT',
  'DELA': 'CFA DELATITE PLANTATION',
  'GBAY': 'CFA GOUGHS BAY - HOWES CREEK',
  'BDAL': 'CFA BAIRNSDALE',
  'BRUT': 'CFA BRUTHEN',
  'MTAM': 'CFA MOSSI - TAMBO',
  'EAGL': 'CFA EAGLEHAWK',
  'CBGP': 'CFA Cobden GROUP',
  'CRRO': 'CFA CROSS ROADS',
  'WVAL': 'CFA WOODVALE',
  'CFRT': 'CFA CAMPBELLS FOREST',
  'RAYW': 'CFA RAYWOOD',
  'SPRH': 'CFA SPRING HILL',
  'YWOU': 'CFA YARRAWONGA',
  'BALM': 'CFA BALMATTUM',
  'COHU': 'CFA COHUNA',
  'ROER': 'CFA ROCHESTER',
  'WAHG': 'CFA WAHGUNYAH',
  'GLBU': 'CFA GLENBURN',
  'SCRC': 'CFA STRATH CREEK-REEDY CREEK',
  'YLIM': 'CFA YEA & LIMESTONE',
  'JHNS': 'CFA BUMBERRAH',
  'CLEM': 'CFA CLEMATIS',
  'TUNG': 'CFA TUNGAMAH',
  'MUCK': 'CFA MUCKATAH',
  'KATA': 'CFA KATAMATITE',
  'MMGP': 'CFA Mount Macedon GROUP',
  'BADD': 'CFA BADDAGINNIE',
  'BRIG': 'CFA BRIGHT',
  'SZGP': 'CFA Leongatha-Kourmburra GROUP',
  'TBGP': 'CFA Tambo GROUP',
  'KORK': 'CFA KOONDROOK',
  'RLGP': 'CFA Maffra GROUP',
  'SWGP': 'CFA Stawell GROUP',
  'WINT': 'CFA WINTON',
  'LBOG': 'CFA LAKE BOGA',
  'KALO': 'CFA KALORAMA & MT DANDENONG',
  'MXGP': 'CFA Metcalfe GROUP',
  'YALN': 'CFA YALLOURN NORTH',
  'KALW': 'CFA KALIMNA WEST',
  'TLOO': 'CFA TOORLOO',
  'BULE': 'CFA BULLENGAROOK',
  'CNGP': 'CFA Kyneton GROUP',
  'CWIN': 'CFA CARDIGAN & WINDERMERE',
  'WSTH': 'CFA WILLUNG SOUTH',
  'WLNG': 'CFA WILLUNG',
  'NAMB': 'CFA NAMBROK',
  'CJNG': 'CFA CARRAJUNG',
  'REDH': 'CFA RED HILL',
  'ELMU': 'CFA ELMHURST',
  'AFLT': 'CFA ALLANS FLAT',
  'ALGP': 'CFA Alexandra GROUP',
  'MEGP': 'CFA Bairnsdale GROUP',
  'NEWR': 'CFA NEWRY',
  'WSEA': 'CFA WINCHELSEA',
  'ERGP': 'CFA Eureka GROUP',
  'YAGL': 'CFA YARRA GLEN',
  'OVGP': 'CFA Ovens Valley GROUP',
  'CAST': 'CFA CASTERTON',
  'WGEE': 'CFA WOORAGEE',
  'GRAN': 'CFA GRANGE',
  'AFRD': 'CFA ALLANSFORD',
  'TALA': 'CFA TALLAROOK',
  'HILD': 'CFA HILLDENE',
  'SHRT': 'CFA SPRINGHURST',
  'WILD': 'CFA WILDWOOD',
  'BULL': 'CFA BULLA',
  'MACA': 'CFA MACARTHUR',
  'LITT': 'CFA LITTLE RIVER',
  'OLIN': 'CFA OLINDA',
  'LANC': 'CFA LANCEFIELD',
  'ROMS': 'CFA ROMSEY',
  'BEAF': 'CFA BEAUFORT',
  'YINS': 'CFA YINNAR SOUTH',
  'FRES': 'CFA FRESHWATER CREEK',
  'NDST': 'CFA NEWSTEAD & DISTRICT',
  'FFRD': 'CFA FRANKLINFORD',
  'CTWN': 'CFA CAMPBELLTOWN',
  'CDGP': 'CFA Cardinia GROUP',
  'ULLI': 'CFA ULLINA',
  'KONA': 'CFA KOOROOCHEANG WERONA',
  'SMET': 'CFA SMEATON',
  'WNEN': 'CFA WOORINEN SOUTH',
  'WAIT': 'CFA WAITCHIE',
  'GBST': 'CFA GOORAMBAT',
  'HLGP': 'CFA Traralgon GROUP',
  'ULTI': 'CFA ULTIMA',
  'TGGP': 'CFA Tallangatta GROUP',
  'GERE': 'CFA GERANGAMETE',
  'FORE': 'CFA FORREST',
  'BARD': 'CFA BARWON DOWNS',
  'HCGP': 'CFA Hopkins - Curdies GROUP',
  'HODD': 'CFA HODDLE\'S CREEK',
  'BARR': 'CFA BARRABOOL',
  'BUFR': 'CFA BUFFALO RIVER',
  'GAPS': 'CFA GAPSTED',
  'MYRU': 'CFA MYRTLEFORD',
  'VICV': 'CFA VICTORIA VALLEY',
  'SDWN': 'CFA STRATHDOWNIE',
  'RENN': 'CFA RENNICK PLANTATION',
  'GRTR': 'CFA GREEN TRIANGLE FOREST PRO',
  'TANJ': 'CFA TANJIL',
  'MAID': 'CFA MAIDEN GULLY',
  'MONG': 'CFA MARONG',
  'CAPE': 'CFA CAPE CLEAR',
  'LINT': 'CFA LINTON',
  'ROJU': 'CFA ROKEWOOD JUNCTION & DIST',
  'HILL': 'CFA HILLSIDE',
  'MTAY': 'CFA MOUNT TAYLOR',
  'IRRE': 'CFA IRREWARRA',
  'BIGP': 'CFA Creswick GROUP',
  'BEEA': 'CFA BEEAC',
  'CWIC': 'CFA CRESWICK',
  'NGAL': 'CFA NARINGAL',
  'KARR': 'CFA KARRAMOMUS',
  'RIGG': 'CFA RIGG\'S CREEK',
  'MIEP': 'CFA MIEPOLL',
  'GLYN': 'CFA GLENLYON',
  'SLEY': 'CFA STANLEY',
  'KING': 'CFA KINGLAKE DISTRICT',
  'CAVE': 'CFA CAVENDISH',
  'KIWE': 'CFA KINGLAKE WEST',
  'BECU': 'CFA BEECHWORTH',
  'WOGI': 'CFA WONTHAGGI',
  'CLON': 'CFA CLONBINANE',
  'ELMO': 'CFA ELMORE',
  'MCAF': 'CFA METCALFE',
  'WINI': 'CFA WINIAM & DISTRICT',
  'PROP': 'CFA PROPODOLLAH',
  'HUGP': 'CFA Hume GROUP',
  'NHIL': 'CFA NHILL',
  'SHOR': 'CFA SHOREHAM',
  'FLIN': 'CFA FLINDERS',
  'AIRE': 'CFA AIREYS INLET',
  'APSL': 'CFA APSLEY',
  'SAYE': 'CFA STRATHFIELDSAYE',
  'EAGP': 'CFA South East GROUP',
  'BCGP': 'CFA Bass Coast GROUP',
  'MUGP': 'CFA Mount Cottrell GROUP',
  'PIAN': 'CFA PIANGIL',
  'WPGP': 'CFA Elmore GROUP',
  'SUTT': 'CFA SUTTON GRANGE & MYRTLE CK',
  'BGRP': 'CFA Beeac GROUP',
  'BWGP': 'CFA Donald GROUP',
  'RUSH': 'CFA RUSHWORTH',
  'CBIN': 'CFA COLBINABBIN',
  'TLEN': 'CFA TOOLLEEN',
  'CORP': 'CFA COROP',
  'COWT': 'CFA COROP WEST',
  'TAGG': 'CFA TAGGERTY',
  'THRN': 'CFA THORNTON',
  'ACHE': 'CFA ACHERON',
  'POMO': 'CFA POMONAL',
  'MARR': 'CFA MARRAWEENY',
  'VTGP': 'CFA Violet Town GROUP',
  'YEGP': 'CFA Yea GROUP',
  'WANT': 'CFA NORTH WARRANDYTE',
  'WDIS': 'CFA WHITFIELD & DISTRICT',
  'TOLM': 'CFA TOLMIE & DISTRICT',
  'TRAU': 'CFA TRAFALGAR',
  'PLND': 'CFA PORTLAND',
  'HOMW': 'CFA HOMEWOOD',
  'MUWD': 'CFA MURRINDINDI & WOODBOURNE',
  'TOLA': 'CFA TOOLANGI',
  'KIEW': 'CFA KIEWA',
  'TALU': 'CFA TALLANGATTA',
  'SCRK': 'CFA SANDY CREEK & CHARLEROI',
  'WDUC': 'CFA WALLINDUC & DISTRICT',
  'BBNK': 'CFA BERRYBANK'
};

export function getStationName(code: string): string {
  // Remove brackets and underscore if present
  const cleanCode = code.replace(/[\[\]_]/g, '');
  
  // Handle P-prefixed codes by checking both P and FS versions
  if (cleanCode.startsWith('P')) {
    return STATION_NAMES[cleanCode] || STATION_NAMES[`FS${cleanCode.slice(1)}`] || code;
  }

  // Handle specialized unit codes
  const specializedMatch = cleanCode.match(/^(R|TB|BA|HZ|PT|LP)(\d+)$/);
  if (specializedMatch) {
    const [, type, number] = specializedMatch;
    const baseStation = STATION_NAMES[`P${number}`] || STATION_NAMES[`FS${number}`];
    if (baseStation) {
      const unitType = {
        'R': 'Rescue',
        'TB': 'Teleboom',
        'BA': 'BA Support',
        'HZ': 'Hazmat',
        'PT': 'Pumper Tanker',
        'LP': 'Ladder Platform'
      }[type];
      return `FRV ${unitType} ${baseStation.split('(')[1].replace(')', '')}`;
    }
  }

  // Handle tanker codes (T1, T2, etc.)
  const tankerMatch = cleanCode.match(/^([A-Z4]+)T[1-9]$/);
  if (tankerMatch) {
    const baseCode = tankerMatch[1];
    const baseName = STATION_NAMES[baseCode];
    if (baseName) {
      return `${baseName} ${cleanCode.slice(4)}`; // Append T1, T2, etc.
    }
  }
  
  return STATION_NAMES[cleanCode] || code;
}

export function formatStationCode(code: string): string {
  return code.replace(/[\[\]_]/g, '');
}